x-mautic-volumes: &mautic-volumes
  - ./mautic/config:/var/www/html/config:z
  - ./mautic/logs:/var/www/html/var/logs:z
  - ./mautic/media/files:/var/www/html/docroot/media/files:z
  - ./mautic/media/images:/var/www/html/docroot/media/images:z
  - ./cron:/opt/mautic/cron:z
  - mautic-docroot:/var/www/html/docroot:z

x-base: &base
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MAUTIC_DB_DATABASE}
    MYSQL_USER: ${MAUTIC_DB_USER}
    MYSQL_PASSWORD: ${MAUTIC_DB_PASSWORD}
    MAUTIC_DB_PORT: ${MAUTIC_DB_PORT}
    PHP_INI_VALUE_DATE_TIMEZONE: ${PHP_INI_VALUE_DATE_TIMEZONE}
    MAUTIC_RUN_CRON_JOBS: true

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mautic-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes: 
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - custom_bridge

  nginx:
    pull_policy: never
    image: mauticnginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - mautic-docroot:/var/www/html/docroot:z
      - ./mautic/media/files:/var/www/html/docroot/media/files:z
      - ./mautic/media/images:/var/www/html/docroot/media/images:z
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - custom_bridge

  mautic_web:
    image: mautic/mautic:6-fpm
    container_name: mautic-web
    restart: unless-stopped
    links:
      - db:mysql
    volumes: *mautic-volumes

    environment:
      <<: *base
      DOCKER_MAUTIC_ROLE: mautic_web
      DOCKER_MAUTIC_LOAD_TEST_DATA: ${DOCKER_MAUTIC_LOAD_TEST_DATA}
      DOCKER_MAUTIC_RUN_MIGRATIONS: "true"
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  mautic_cron:
    image: mautic/mautic:6-fpm
    container_name: mautic-cron
    restart: unless-stopped
    links:
      - db:mysql
    volumes: *mautic-volumes
    environment:
      <<: *base
      DOCKER_MAUTIC_ROLE: mautic_cron
      DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL: 2
      DOCKER_MAUTIC_WORKERS_CONSUME_HIT: 2
      DOCKER_MAUTIC_WORKERS_CONSUME_FAILED: 2
    depends_on:
      mautic_web:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - custom_bridge

  mautic_worker:
    image: mautic/mautic:6-fpm
    container_name: mautic-worker
    restart: unless-stopped
    links:
      - db:mysql
    volumes: *mautic-volumes
    environment:
      <<: *base
      DOCKER_MAUTIC_ROLE: mautic_worker
      DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL: 2
      DOCKER_MAUTIC_WORKERS_CONSUME_HIT: 2
      DOCKER_MAUTIC_WORKERS_CONSUME_FAILED: 2
    depends_on:
      mautic_web:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - default

volumes:
  mysql-data:
  mautic-docroot:

networks:
  custom_bridge:
    driver: bridge