x-mautic-volumes: &mautic-volumes
  - ./mautic/config:/var/www/html/config:z
  - ./mautic/logs:/var/www/html/var/logs:z
  - ./mautic/media/files:/var/www/html/docroot/media/files:z
  - ./mautic/media/images:/var/www/html/docroot/media/images:z
  - ./cron:/opt/mautic/cron:z
  - mautic-docroot:/var/www/html/docroot:z

x-base: &base
    PHP_INI_VALUE_DATE_TIMEZONE: ${PHP_INI_VALUE_DATE_TIMEZONE}
    MAUTIC_RUN_CRON_JOBS: true
    MARIADB_ROOT_PASSWORD: ${MAUTIC_DB_ROOT_PASSWORD}
    MARIADB_DATABASE: ${MAUTIC_DB_DATABASE}
    MARIADB_USER: ${MAUTIC_DB_USER}
    MARIADB_PASSWORD: ${MAUTIC_DB_PASSWORD}

services:
  db:
    image: alpine/mariadb:11.4.9
    restart: unless-stopped
    container_name: mautic-db
    command: 
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-allowed-packet=128M
      - --innodb-log-file-size=256M
      - --innodb-buffer-pool-size=512M
    environment:
      MARIADB_ROOT_PASSWORD: ${MAUTIC_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MAUTIC_DB_DATABASE}
      MARIADB_USER: ${MAUTIC_DB_USER}
      MARIADB_PASSWORD: ${MAUTIC_DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    volumes: 
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - custom_bridge

  nginx:
    pull_policy: never
    image: mauticnginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - mautic-docroot:/var/www/html/docroot:z
      - ./mautic/media/files:/var/www/html/docroot/media/files:z
      - ./mautic/media/images:/var/www/html/docroot/media/images:z
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - custom_bridge

  mautic_web:
    image: mautic/mautic:6-fpm
    container_name: mautic-web
    restart: unless-stopped
    volumes: *mautic-volumes
    environment:
      <<: *base
      DOCKER_MAUTIC_ROLE: mautic_web
      DOCKER_MAUTIC_LOAD_TEST_DATA: ${DOCKER_MAUTIC_LOAD_TEST_DATA}
      DOCKER_MAUTIC_RUN_MIGRATIONS: "true"
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      db:
        condition: service_healthy
    networks:
      - custom_bridge

  mautic_cron:
    image: mautic/mautic:6-fpm
    container_name: mautic-cron
    restart: unless-stopped
    volumes: *mautic-volumes
    environment:
      <<: *base
      DOCKER_MAUTIC_ROLE: mautic_cron
      DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL: 2
      DOCKER_MAUTIC_WORKERS_CONSUME_HIT: 2
      DOCKER_MAUTIC_WORKERS_CONSUME_FAILED: 2
    depends_on:
      mautic_web:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - custom_bridge

  mautic_worker:
    image: mautic/mautic:6-fpm
    container_name: mautic-worker
    restart: unless-stopped
    volumes: *mautic-volumes
    environment:
      <<: *base
      DOCKER_MAUTIC_ROLE: mautic_worker
      DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL: 2
      DOCKER_MAUTIC_WORKERS_CONSUME_HIT: 2
      DOCKER_MAUTIC_WORKERS_CONSUME_FAILED: 2
    depends_on:
      mautic_web:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - custom_bridge

volumes:
  mariadb-data:
  mautic-docroot:

networks:
  custom_bridge:
    driver: bridge
